[package]
name = "toolkit-api"
version = "0.1.0"
authors = ["Joshua Paul Chan <joshpaulchan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"

[[bin]]
name = "toolkit-api"
path = "main.rs"
