version: "2.1"

services:
  db:
    image: cassandra:3.11
    restart: unless-stopped
    ports:
      - "7000:7000"
    env_file: dev.env
  api:
    image: gcr.io/joshpaulchan/toolkit-api:${BRANCH:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    env_file: dev.env
    depends_on:
      - db
    ports:
      - "3030:3030"
